dex2oat.cpp: add missing include
../../../../src/main/jni/dex2oat.cpp:37:5: error: use of undeclared identifier 'realpath'
     37 |     realpath("bin/dex2oat32", dex2oat32);
        |     ^
  ../../../../src/main/jni/dex2oat.cpp:38:5: error: use of undeclared identifier 'realpath'
     38 |     realpath("bin/dex2oat64", dex2oat64);
        |     ^
  ../../../../src/main/jni/dex2oat.cpp:80:9: error: use of undeclared identifier 'exit'; did you mean '_exit'?
     80 |         exit(1);
        |         ^~~~
        |         _exit
  /usr/local/lib/android/sdk/ndk/29.0.13599879/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/include/unistd.h:80:17: note: '_exit' declared here
     80 | __noreturn void _exit(int __status);
        |                 ^
  3 errors generated.